### ISSUE TITLE
The Terminal Commands and Touch ID and sudoers

### ISSUE THREAD

**Issue by tjluoma** [jordibruin/cooldown#1]
The user could put the Terminal commands into `shudders` or could run the app via `sudo` to avoid Touch ID, but that may not be ideal.

**Comment by skynet01** [comment]
Yeah @tjluoma is right, for example if your username is skynet you put skynet ALL=(ALL) NOPASSWD: /usr/bin/pmset in /etc/sudoers.d/pmset to allow user skynet to run pmset without entering their password (you still have to use sudo; it just won’t ask for a password). Maybe upon install you can ask users if they want that file created and give them a warning about security implications of it, I for one don't see an issue with that :)

**Comment by jordibruin** [comment]
I fixed this already by using the shortcuts, so the sudo is no longer necessary if the user sets up the shortcuts. Thanks for the suggestion though, I did not know about this approach!
